### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by kra53n** [helpcomputer/nydd#1]
> some recommendations for your code
> as I understand you could already know this things

## loops

You could use iterating instead of `range(len(obj))` expression.
https://github.com/helpcomputer/nydd/blob/d0460d11ba5f3c53b8d55f1c8de8348ce90254a0/src/utils.py#L64-L70
Like this:
```python
    for line in lines:
        thisChunk.append(line)
        count += 1
        if count == lines_high:
            count = 0
            chunks.append(thisChunk)
            thisChunk = []
```

And it looks more readable

---

If you need `i` in this situation I think it will be better to use `enumerate` function:

```python
    for i, _ in enumerate(lines):
        thisChunk.append(lines[i])
        count += 1
        if count == lines_high:
            count = 0
            chunks.append(thisChunk)
            thisChunk = []
```

It is just an example. I think the code above is bad because you could just iterate object.

---

As you code in Python it is not necessary write brackets near the expression:
https://github.com/helpcomputer/nydd/blob/d0460d11ba5f3c53b8d55f1c8de8348ce90254a0/src/actor.py#L65

```py
    while total_moved_abs < abs_dx: 
```

## functions

If you are in situation when every condition must have `True` value you can use `all` function or
`any` if at least one value have `True`.

https://github.com/helpcomputer/nydd/blob/d0460d11ba5f3c53b8d55f1c8de8348ce90254a0/src/rect.py#L5-L8
```py
    return all(x1 < x2 + w2, 
               x1 + w1 > x2,
               y1 < y2 + h2,
               y1 + h1 > y2)
```

> sorry for my English

**Comment by helpcomputer** [comment]
Thanks, some of these things I didn't know!

**Comment by helpcomputer** [comment]
Thank you, I've added these changes.

**Comment by kra53n** [comment]
Oh... I did a mistake with `all` and `any` functions.

`all(True, 1, 'string')` will not work because of all takes only 1 argument. So it must be `all((True, 1, 'string'))`

**Comment by helpcomputer** [comment]
> Oh... I did a mistake with `all` and `any` functions.
> 
> `all(True, 1, 'string')` will not work because of all takes only 1 argument. So it must be `all((True, 1, 'string'))`

I fixed it now! I wasn't using the functions so I didn't notice.
